### ISSUE TITLE
kcp cut down

### ISSUE THREAD

**Issue by wjx0912** [privch/shadowsocks-android-modified#1]
the official version 4.8.3 works fine with kcp.

but the shadowsocks-android-modified  can't support kcp, does the plugin function cut down?

thanks.

**Comment by xinlake** [comment]
Yep, a lot of features have been removed actually, and this app is no longer maintenance, sorry to tell you this.

But, There will be a new Flutter app instead, which built with Flutter and all new Android application components. Also may support V2Ray protocol, Stay tuned .


mail: xinlake@outlook.com

________________________________

**Comment by wjx0912** [comment]
@xinlake thanks~
